routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Artisan::call('storage:link');

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [App\Http\Controllers\FrontOfficeController::class, 'HomePage']);

Route::get('/contact', [App\Http\Controllers\FrontOfficeController::class, "Contact"])->name('contact');

Route::get('/about', [App\Http\Controllers\FrontOfficeController::class, "About"])->name('about');

Route::get('/services', [App\Http\Controllers\FrontOfficeController::class, "Services"])->name('services');

// Route::get('/detailproject', [App\Http\Controllers\FrontOfficeController::class, "showProject"])->name('detailproject');

Route::post('/contacter', [App\Http\Controllers\ContactRequestController::class, "addContactRequest"])->name('contacter');

// Route::post('/footer', [App\Http\Controllers\NewLetterController::class, "addEmail"])->name('footer');


// Route::get('/portfolios', [App\Http\Controllers\FrontOfficeController::class, "IndexProjects"])->name('portfolios');

Route::resource('slides', App\Http\Controllers\SlideController::class);

Route::resource('projects', App\Http\Controllers\ProjectController::class);

Route::resource('categoryProjects', App\Http\Controllers\CategoryProjectController::class);

Route::resource('servicios', App\Http\Controllers\ServicioController::class);

Route::resource('typeServices', App\Http\Controllers\TypeServicesController::class);

Route::resource('contactRequests', App\Http\Controllers\ContactRequestController::class);

Route::post('ckeditor/upload', [App\Http\Controllers\CKEditorController::class, "upload"])->name('upload');

Route::resource('settings', App\Http\Controllers\SettingController::class);

Route::resource('newLetters', App\Http\Controllers\NewLetterController::class);

Route::resource('teams', App\Http\Controllers\TeamController::class);

Route::resource('blogs', App\Http\Controllers\BlogController::class);

Route::resource('categoryBlogs', App\Http\Controllers\CategoryBlogController::class);


Route::resource('users', App\Http\Controllers\UserController::class);


Route::resource('partners', App\Http\Controllers\PartnersController::class);


Route::resource('candidacies', App\Http\Controllers\CandidacyController::class);

app/Models/NewLetter.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class NewLetter
 * @package App\Models
 * @version April 29, 2021, 5:07 pm UTC
 *
 */
class NewLetter extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'new_letters';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'email',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'email' => 'string',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];


}

app/Http/Controllers/NewLetterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateNewLetterRequest;
use App\Http\Requests\UpdateNewLetterRequest;
use App\Repositories\NewLetterRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\NewLetter;
use Illuminate\Http\Request;
use Flash;
use Response;

class NewLetterController extends AppBaseController
{
    /** @var  NewLetterRepository */
    private $newLetterRepository;

    public function __construct(NewLetterRepository $newLetterRepo)
    {
        $this->newLetterRepository = $newLetterRepo;
    }

    /**
     * Display a listing of the NewLetter.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $newLetters = NewLetter::orderBy('id', 'desc')->paginate(10);

        // $newLetters = $this->newLetterRepository->all();

        return view('new_letters.index')
            ->with('newLetters', $newLetters);
    }

    /**
     * Show the form for creating a new NewLetter.
     *
     * @return Response
     */
    public function create()
    {
        return view('new_letters.create');
    }

    /**
     * Store a newly created NewLetter in storage.
     *
     * @param CreateNewLetterRequest $request
     *
     * @return Response
     */
    public function store(CreateNewLetterRequest $request)
    {
        $input = $request->all();

        $newLetter = $this->newLetterRepository->create($input);

        Flash::success('New Letter saved successfully.');

        return redirect(route('newLetters.index'));
    }

    /**
     * Display the specified NewLetter.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $newLetter = $this->newLetterRepository->find($id);

        if (empty($newLetter)) {
            Flash::error('New Letter not found');

            return redirect(route('newLetters.index'));
        }

        return view('new_letters.show')->with('newLetter', $newLetter);
    }

    /**
     * Show the form for editing the specified NewLetter.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $newLetter = $this->newLetterRepository->find($id);

        if (empty($newLetter)) {
            Flash::error('New Letter not found');

            return redirect(route('newLetters.index'));
        }

        return view('new_letters.edit')->with('newLetter', $newLetter);
    }

    /**
     * Update the specified NewLetter in storage.
     *
     * @param int $id
     * @param UpdateNewLetterRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateNewLetterRequest $request)
    {
        $newLetter = $this->newLetterRepository->find($id);

        if (empty($newLetter)) {
            Flash::error('New Letter not found');

            return redirect(route('newLetters.index'));
        }

        $newLetter = $this->newLetterRepository->update($request->all(), $id);

        Flash::success('New Letter updated successfully.');

        return redirect(route('newLetters.index'));
    }

    /**
     * Remove the specified NewLetter from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $newLetter = $this->newLetterRepository->find($id);

        if (empty($newLetter)) {
            Flash::error('New Letter not found');

            return redirect(route('newLetters.index'));
        }

        $this->newLetterRepository->delete($id);

        Flash::success('New Letter deleted successfully.');

        return redirect(route('newLetters.index'));
    }


    public function addEmail(CreateNewLetterRequest $request)
    {
        $data = $request->validate([
            'name' => 'required',
            'email' => 'required | email'
        ]);

        $newLetter = new NewLetter();
        $newLetter->name = $data['name'];
        $newLetter->email = $data['email'];

        $newLetter->save();

        session()->flash('success', "Message envoyé enregistrée avec success");

        return redirect()->back();
    }
}

resources/views/new_letters/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create New Letter</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'newLetters.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('new_letters.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('newLetters.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/new_letters/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit New Letter</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($newLetter, ['route' => ['newLetters.update', $newLetter->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('new_letters.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('newLetters.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/new_letters/index.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
     Notre Newsletters | {{ config('app.name') }}
@endsection

@section('content')

     <div class="page-heading">
         <div class="page-title">
             <div class="row">
                 <div class="col-12 col-md-6 order-md-1 order-last">
                     <h3 style="color: white !important">Notre Newsletters</h3>
                     <p class="text-subtitle text-muted" style="color: white !important">La liste de tous nos Emails Clients</p>
                 </div>
                 <div class="col-12 col-md-6 order-md-2 order-first">
                     {{-- <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                         <ol class="breadcrumb">
                             <a class="btn btn-danger float-right"href="{{ route('categoryBlogs.create') }}">Ajouter une Catégorie</a>
                         </ol>
                     </nav> --}}
                 </div>
             </div>
         </div>
         <section class="section">
             <div class="card">
                 @include('new_letters.table')
             </div>
         </section>
     </div>

 @endsection

resources/views/new_letters/show.blade.php
@extends('BackOffice_layouts.master')

@section('title')
    Notre Newsletters | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Détails de L'Email</h3>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <a class="btn btn-danger float-right"href="{{ route('newLetters.index') }}">Retour</a>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="content px-3">
            <div class="card">
                <div class="card-body">
                    @include('new_letters.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/new_letters/show_fields.blade.php
<div class="row">
    <!-- Name At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('name', 'Nom du Client:') !!}
            <p>{{ $newLetter->name }}</p>
        </div>
    </div>
    <!-- email At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            <p>{{ $newLetter->email }}</p>
        </div>
    </div>
</div>

<div class="row mt-3">
    <!-- Created At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('created_at', 'Crée à:') !!}
            <p>{{ $newLetter->created_at }}</p>
        </div>
    </div>
    <!-- Updated At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('updated_at', 'Modifié à:') !!}
            <p>{{ $newLetter->updated_at }}</p>
        </div>
    </div>
</div>

resources/views/new_letters/table.blade.php
<div class="card-body">

    <table class="table table-striped" id="table1">
        <thead>
            <tr>
                <th>Nom & Prenoms</th>
                <th>Email</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($newLetters as $newLetter)
                <tr>

                    <td>{{ $newLetter->name }}</td>
                    <td>{{ $newLetter->email }}</td>
                    <td width="120">
                        {!! Form::open(['route' => ['newLetters.destroy', $newLetter->id], 'method' => 'delete']) !!}
                            <div class="btn-group mb-2" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-primary"><a href="{{ route('newLetters.show', [$newLetter->id]) }}" class='badge badge-pill badge-primary'>
                                    Voir
                                </a></button>
                                {!! Form::button('Supprimer', ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                            </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>